spring:
  application:
    name: skib

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mariadb://localhost:3306/SKIB
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    mongodb:
      uri: mongodb+srv://yoonalim2003:${MONGO_PASSWORD}@cluster0.9asfqrd.mongodb.net/SKIB?retryWrites=true&w=majority
      database: SKIB

app:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
