spring:
  application:
    name: skib

  config:
    import: optional:file:./.env.properties

  datasource:
    url: ${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect

  data:
    mongodb:
      uri: ${MONGO_URI_PROD}
      database: sk-team-09

jwt:
  secret-key: ${JWT_SECRET_KEY}
