package com.t1f5.skib.global.enums;

public enum DocumentStatus {
  UPLOAD_COMPLETED,
  PREPROCESSING_START,
  PARSING_DOCUMENT,
  ANALYZING_CONTENT,
  SUMMARIZING,
  STORING_VECTORDB,
  SUMMARY_COMPLETED,
  FAILED
}
