package com.t1f5.skib.global.enums;

public enum TestStatus {
    TEST_GENERATION_STARTED,
    LOADING_TEST_PLAN,
    REFLECTING_TEST_PLAN,
    RETRIEVING_CONTEXTS,
    PREPROCESSING_CONTEXTS,
    GENERATING_QUESTIONS,
    POSTPROCESSING_QUESTIONS,
    FINALIZING_RESULTS,
    COMPLETED,
    FAILED
}
