apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sk-team-09-backend
  namespace: sk-team-09
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/enable-websocket: "true" # ✅ 추가
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600" # ✅ 추천
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600" # ✅ 추천
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1" # ✅ 중요
spec:
  ingressClassName: public-nginx
  rules:
    - host: skib-backend.skala25a.project.skala-ai.com
      http:
        paths:
          - path: /ws # ✅ WebSocket 경로 추가
            pathType: Prefix
            backend:
              service:
                name: sk-team-09-backend
                port:
                  number: 8080
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: sk-team-09-backend
                port:
                  number: 8080
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: sk-team-09-backend
                port:
                  number: 8081
          - path: /swagger-ui
            pathType: Prefix
            backend:
              service:
                name: sk-team-09-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sk-team-09-backend
                port:
                  number: 8080
  tls:
    - hosts:
        - "skib-backend.skala25a.project.skala-ai.com"
      secretName: skib-backend-tls-cert
