apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: sk-team-09
type: Opaque
data:
  mongo-uri-prod: bW9uZ29kYjovL3Jvb3Q6U2thbGEyNWEhMjMlMjRAYWY3NjliZWQ2MTQ3NjQyOTQ4NmY5MDAzYjhhMjgyNjAtMzk2YjQ1Zjc4Yzg5NjE0MWVsYi5hcC1ub3J0aGVhc3QtMi5hbWF6b25hd3MuY29tOjI3MDE3Lz9hdXRoU291cmNlPWFkbWlu

apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: sk-team-09
type: Opaque
data:
  jwt-secret-key: Z3FlYWo2SThJL3B6ZHRlUkJkcEs3ZHQwa0Jxclo0MkxvYzBvc2pUcHVrUVM0UCtOSk50UEtyemdGRm1QWTdjOTJFYjR6ZThLTk9COURhUnJjSUpOU1E9PQ==