name: CI/CD Full Deploy to K8s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_REGISTRY: docker.io/yoonalim2003
      IMAGE_NAME: sk-team-09-backend
      IMAGE_TAG_BASE: 1.0.0
      K8S_NAMESPACE: default
      GIT_USER_NAME: yoonali
      GIT_USER_EMAIL: yoonalim2003@gmail.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle (skip tests)
        run: ./gradlew clean build -x test

      - name: Generate FINAL_IMAGE_TAG
        id: image_tag
        run: |
          HASH=$(date +%s%N | sha256sum | cut -c1-12)
          FINAL_TAG="${{ env.IMAGE_TAG_BASE }}-${GITHUB_RUN_NUMBER}-${HASH}"
          echo "FINAL_IMAGE_TAG=$FINAL_TAG" >> $GITHUB_ENV
          echo "Final tag: $FINAL_TAG"

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.REGISTRY_USERNAME }} # 예: yoonalim2003
          password: ${{ secrets.REGISTRY_PASSWORD }} # 비밀번호 또는 PAT

      - name: Build and Push Docker Image
        run: |
          docker build --platform linux/amd64 -t $IMAGE_REGISTRY/$IMAGE_NAME:$FINAL_IMAGE_TAG .
          docker push $IMAGE_REGISTRY/$IMAGE_NAME:$FINAL_IMAGE_TAG

      - name: Update deploy.yaml with new image tag
        run: |
          sed -i "s|^[[:space:]]*image:.*\$|          image: $IMAGE_REGISTRY/$IMAGE_NAME:$FINAL_IMAGE_TAG|" ./k8s/deploy.yaml
          echo "Updated deploy.yaml:"
          cat ./k8s/deploy.yaml

      - name: Commit and Push updated deploy.yaml
        run: |
          git config user.name "${{ env.GIT_USER_NAME }}"
          git config user.email "${{ env.GIT_USER_EMAIL }}"
          git add ./k8s/deploy.yaml || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[AUTO] Update deploy.yaml with image $FINAL_IMAGE_TAG"
            git push
          fi

      - name: Set up latest kubectl
        uses: azure/setup-kubectl@v3

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f ./k8s/deploy.yaml -n $K8S_NAMESPACE
